module.exports = [
    {
        id: 1,
        user_id: "1",
        room_id: "1",
        comment: "PLACEHOLDER COMMENT",
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 4.5,
        storyline_rating: 4.5,
        staff_rating: 4.5,
    },
    {
        id: 2,
        user_id: "1",
        room_id: "2",
        comment: "PLACEHOLDER COMMENT",
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 4.5,
        storyline_rating: 4.5,
        staff_rating: 4.5,
    },
    {
        id: 3,
        user_id: "1",
        room_id: "3",
        comment: "PLACEHOLDER COMMENT",
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 4.5,
        storyline_rating: 4.5,
        staff_rating: 4.5,
    },
    {
        id: 4,
        user_id: "1",
        room_id: "4",
        comment: "PLACEHOLDER COMMENT",
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 4.5,
        storyline_rating: 4.5,
        staff_rating: 4.5,
    },
    {
        id: 5,
        user_id: "2",
        room_id: "1",
        comment: "PLACEHOLDER COMMENT",
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 4.5,
        storyline_rating: 4.5,
        staff_rating: 4.5,
    },
];
