module.exports = [
    {
        id: 1,
        user_id: "2",
        room_id: "1",
        comment: "Great adventure with challenging puzzles!",
        atmosphere_rating: 5,
        puzzle_fairness_rating: 4,
        tech_rating: 5,
        storyline_rating: 4,
        staff_rating: 5,
      },
      {
        id: 2,
        user_id: "2",
        room_id: "2",
        comment: "Mysterious and thrilling experience!",
        atmosphere_rating: 4,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 5,
        staff_rating: 4,
      },
      {
        id: 3,
        user_id: "3",
        room_id: "1",
        comment: "Budget-friendly fun with fair puzzles.",
        atmosphere_rating: 3,
        puzzle_fairness_rating: 4,
        tech_rating: 3,
        storyline_rating: 3,
        staff_rating: 4,
      },
      {
        id: 4,
        user_id: "4",
        room_id: "4",
        comment: "A mind-blowing journey through space! The staff unfortunately weren't accomodating to our needs, however.",
        atmosphere_rating: 5,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 2,
        staff_rating: 2,
      },
      {
        id: 5,
        user_id: "2",
        room_id: "5",
        comment: "Magical adventure with immersive puzzles!",
        atmosphere_rating: 4,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 4,
        staff_rating: 4,
      },
      {
        id: 6,
        user_id: "1",
        room_id: "3",
        comment: "Absolutely thrilling experience! Highly recommended.",
        atmosphere_rating: 5,
        puzzle_fairness_rating: 4,
        tech_rating: 5,
        storyline_rating: 5,
        staff_rating: 5,
      },
      {
        id: 7,
        user_id: "2",
        room_id: "2",
        comment: "Challenging puzzles and great storyline!",
        atmosphere_rating: 4,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 4,
        staff_rating: 4,
      },
      {
        id: 8,
        user_id: "3",
        room_id: "5",
        comment: "Exciting adventure with clever puzzles!",
        atmosphere_rating: 5,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 5,
        staff_rating: 5,
      },
      {
        id: 9,
        user_id: "4",
        room_id: "4",
        comment: "Unique and immersive escape room experience!",
        atmosphere_rating: 4,
        puzzle_fairness_rating: 5,
        tech_rating: 4,
        storyline_rating: 4,
        staff_rating: 4,
      },
      {
        id: 10,
        user_id: "3",
        room_id: "5",
        comment: "Highly enjoyable adventure with challenging puzzles!",
        atmosphere_rating: 5,
        puzzle_fairness_rating: 4,
        tech_rating: 5,
        storyline_rating: 5,
        staff_rating: 5,
      },
];
