module.exports = [
    {
        id: '1',
        'user_id': "1",
        'name': 'Adventure Quest',
        'description': 'Embark on a thrilling adventure with mind-bending puzzles.',
        'theme': 'Adventure',
        'address': '123 Main Street, Cityville',
        'cost': 'premium',
        'group_size': 4,
        'duration': 60,
        'difficulty': 'Moderate',
        'success_rate': 0.75,
        'overall_rating': 4.5,
        'atmosphere_rating': 4.0,
        'puzzle_fairness_rating': 4.2,
        'tech_rating': 3.8,
        'storyline_rating': 4.5,
        'staff_rating': 4.8,
        'thumbnail': 'path/to/thumbnail1.jpg',
        'website_url': 'https://www.adventurequest.com',
      },
      {
        id: '2',
        'user_id': "1",
        'name': 'Mystery Mansion Escape',
        'description': 'Explore the mysterious mansion and solve the mystery.',
        'theme': 'Mystery',
        'address': '456 Oak Avenue, Townsville',
        'cost': 'affordable',
        'group_size': 6,
        'duration': 75,
        'difficulty': 'Challenging',
        'success_rate': 0.65,
        'overall_rating': 4.2,
        'atmosphere_rating': 4.5,
        'puzzle_fairness_rating': 4.0,
        'tech_rating': 4.2,
        'storyline_rating': 4.8,
        'staff_rating': 4.6,
        'thumbnail': 'path/to/thumbnail2.jpg',
        'website_url': 'https://www.mysterymansionescape.com',
      },
      {
        id: '3',
        'user_id': "1",
        'name': 'Budget Breakout',
        'description': 'Solve puzzles on a budget and experience the thrill.',
        'theme': 'Budget',
        'address': '789 Pine Street, Villagetown',
        'cost': 'budget',
        'group_size': 8,
        'duration': 45,
        'difficulty': 'Easy',
        'success_rate': 0.85,
        'overall_rating': 4.0,
        'atmosphere_rating': 3.5,
        'puzzle_fairness_rating': 4.5,
        'tech_rating': 3.2,
        'storyline_rating': 3.8,
        'staff_rating': 4.0,
        'thumbnail': 'path/to/thumbnail3.jpg',
        'website_url': 'https://www.budgetbreakout.com',
      },
      {
        id: '4',
        'user_id': "5",
        'name': 'Space Odyssey',
        'description': 'Embark on a space-themed adventure with cosmic challenges.',
        'theme': 'Space',
        'address': '101 Galaxy Avenue, Spacetown',
        'cost': 'premium',
        'group_size': 5,
        'duration': 90,
        'difficulty': 'Hard',
        'success_rate': 0.60,
        'overall_rating': 4.8,
        'atmosphere_rating': 4.7,
        'puzzle_fairness_rating': 4.5,
        'tech_rating': 4.5,
        'storyline_rating': 4.9,
        'staff_rating': 4.9,
        'thumbnail': 'path/to/thumbnail4.jpg',
        'website_url': 'https://www.spaceodyssey.com',
      },
      {
        id: '5',
        'user_id': "5",
        'name': 'Enchanted Escape',
        'description': 'Step into a magical world and solve enchanting puzzles.',
        'theme': 'Fantasy',
        'address': '567 Magic Lane, Fairytale City',
        'cost': 'affordable',
        'group_size': 3,
        'duration': 60,
        'difficulty': 'Moderate',
        'success_rate': 0.70,
        'overall_rating': 4.3,
        'atmosphere_rating': 4.5,
        'puzzle_fairness_rating': 4.2,
        'tech_rating': 3.9,
        'storyline_rating': 4.4,
        'staff_rating': 4.7,
        'thumbnail': 'path/to/thumbnail5.jpg',
        'website_url': 'https://www.enchantedescape.com',
      },

]