module.exports = [
    {
        id: "f7e0238f-c9df-4fd6-8880-af4d6ba24cd0",
        user_id: "036596ce-602e-4e81-a3b6-088416df75c2",
        name: "Mystery Mansion",
        description:
            "Explore the haunted mansion and uncover its dark secrets.",
        theme: "Haunted House",
        group_size: 4,
        duration: 60,
        address: "123 Elm Street",
        cost: "Premium",
        difficulty: "Intermediate",
        completion_rate: 0.75,
        overall_rating: 4.26,
        atmosphere_rating: 4.0,
        puzzle_fairness_rating: 4.2,
        tech_rating: 3.8,
        storyline_rating: 4.5,
        staff_rating: 4.8,
        thumbnail: "path/to/thumbnail1.jpg",
        website_url: "https://www.mysterymansion.com",
    },
    {
        id: "f6057e71-86bd-4117-bd14-aeb216134bc6",
        user_id: "ddd287ee-c482-44fb-a671-dc949fb236de",
        name: "Lost Temple Adventure",
        description:
            "Embark on an expedition to find ancient treasures hidden within a forgotten temple.",
        theme: "Adventure",
        group_size: 4,
        duration: 60,
        address: "456 Oak Avenue",
        cost: "Affordable",
        difficulty: "Challenging",
        completion_rate: 0.65,
        overall_rating: 4.42,
        atmosphere_rating: 4.5,
        puzzle_fairness_rating: 4.0,
        tech_rating: 4.2,
        storyline_rating: 4.8,
        staff_rating: 4.6,
        thumbnail: "path/to/thumbnail2.jpg",
        website_url: "www.losttempleadventure.com",
    },
    {
        id: "c7baf16b-ffe0-4c7c-99e4-774a0ae281e2",
        user_id: "ddd287ee-c482-44fb-a671-dc949fb236de",
        name: "Cyberpunk Escape",
        description:
            "Navigate through a futuristic cityscape filled with technological puzzles and challenges.",
        theme: "Cyberpunk",
        group_size: 4,
        duration: 60,
        address: "789 Maple Street",
        cost: "Budget",
        difficulty: "Beginner",
        completion_rate: 0.85,
        overall_rating: 3.2,
        atmosphere_rating: 2.5,
        puzzle_fairness_rating: 4.5,
        tech_rating: 3.2,
        storyline_rating: 3.8,
        staff_rating: 2.0,
        thumbnail: "path/to/thumbnail3.jpg",
        website_url: "www.cyberpunkescape.com",
    },
];
