module.exports = [
    {
        id: 1,
        username: "owner",
        password: "password",
        email: "test@Email1",
        thumbnail: "test",
        is_owner: true,
    },
    {
        id: 2,
        username: "user",
        password: "password",
        email: "test@Email2",
        thumbnail: "test",
        is_owner: false,
    },
    {
        id: 3,
        username: "user3",
        password: "password",
        email: "test@Email3",
        thumbnail: "test",
        is_owner: false,
    },
    {
        id: 4,
        username: "user4",
        password: "password",
        email: "test@Email4",
        thumbnail: "test",
        is_owner: false,
    },
    {
        id: 5,
        username: "owner5",
        password: "password",
        email: "test@Email5",
        thumbnail: "test",
        is_owner: true,
    },
];
