module.exports = [
    {
        id: 1,
        username: "testName1",
        password: "testPass1",
        email: "testEmail1",
        thumbnail: "test",
        is_owner: true,
      },
      {
        id: 2,
        username: "testName2",
        password: "testPass2",
        email: "testEmail2",
        thumbnail: "test",
        is_owner: false,
      },
      {
        id: 3,
        username: "testName3",
        password: "testPass3",
        email: "testEmail3",
        thumbnail: "test",
        is_owner: false,
      },
      {
        id: 4,
        username: "testName4",
        password: "testPass4",
        email: "testEmail4",
        thumbnail: "test",
        is_owner: false,
      },
      {
        id: 5,
        username: "testName5",
        password: "testPass5",
        email: "testEmail5",
        thumbnail: "test",
        is_owner: true,
      },
]